[build]
  command = "npm run build"
  publish = "out"

# Remove Next.js plugin as we're using static export
# [[plugins]]
#   package = "@netlify/plugin-nextjs"

# Handle client-side routing and SPA fallbacks
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache control for static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache control for JavaScript files
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 